#! /bin/bash
# Code snippet/template generator

# For debugging.
#set -x

# TODO(ds) Just deals with classes for now, extend for other kinds
# eg new pimpl Xyx, new visitor Xyz and have a case statement to 
# call a sub .sh file for each kind.
if [ "$1" != "class" ]; then 
  echo "Try: new class subdir/ClassName";
  exit;
fi

# Check that the target name is given.
if [ "$#" -lt 2 ]; then
  echo 'Give a class name, eg ./new subdir/MyNewClass'
  exit;
fi

# Location of this script (and hence the template sources).
template_base=$(dirname $0)

# Relative path of the given target.
subdir=$(dirname $2)

# Target name (without path).
class=$(basename $2)

# Check that the relative path exists.
if [ ! -d "$subdir" ]; then
  echo "Path $subdir not found.";
  exit;
fi

# Replace Xy with _xy and remove leading underscore.
function Camel2Hacker {
  echo $(echo $1 |sed 's/\([A-Z]\)/_\l\1/g' |sed 's/^_//')
}

# Replace _x with X and capitalize the first char.
function Hacker2Camel {
  echo $(echo $1 |sed 's/_\([a-z]\)/\u\1/g' |sed 's/^\([a-z]\)/\u\1/')
}

# Make cc and h paths.
class_hacker=$(Camel2Hacker $class)
cc=$class_hacker".cc"
h=$class_hacker".h"
cc_path=$subdir"/"$cc
h_path=$subdir"/"$h

# Don't overwrite an existing class.
if [ -f $cc_path ] || [ -f $h_path ]; then
  echo $cc_path" or "$h_path" already exist.";
  exit;
fi

# Copy templates to targets.
cp $template_base'/'class.cc $cc_path
cp $template_base'/'class.h $h_path

# Update copyright date.
YYYY=$(echo $(date) |grep -Po '\d{4}')
sed -i "1 s/@YYYY@/$YYYY/" $cc_path $h_path

# Get the repo name (by working up the path until we hit the .git folder).
repo=$(
  basename $(
    x=`pwd`; 
    while [ "$x" != "/" ]; do 
      x=`dirname "$x"`; 
      echo "$x"; 
      if [ `find "$x" -maxdepth 1 -name .git` ]; then 
        break; 
      fi; 
    done
  )
)

# Update the repo name.
sed -i "s/@REPO@/$repo/" $cc_path $h_path

# Update the subdir.
sed -i "s/@SUBDIR@/${subdir^^}/" $cc_path $h_path

# Update the class names.
sed -i "s/@CLASS@/${class_hacker^^}/g" $cc_path $h_path
sed -i "s/@Class@/$class/g" $cc_path $h_path

# Update the include header (2nd sed escapes any path separators).
sed -i "s/@h_path@/$(echo $h_path |sed 's/\//\\\//g')/" $cc_path

# Add the .cc and .h to the repo.
git add $cc_path $h_path
